# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Lint • Test • Snapshot
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: ['1.22.x']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Lint (golangci)
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.57.2
          args: --timeout 5m

      - name: govulncheck
        uses: golang/govulncheck-action@v1

      - name: Run unit‑tests with race & coverage
        run: |
          go test -race -covermode=atomic -coverprofile=coverage.out ./...

      - name: Upload snapshot artifacts
        uses: actions/upload-artifact@v4
        with:
          name: snapshot-${{ github.sha }}
          path: dist/**
