name: Version

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/commit-analyzer@^9.0.2
            @semantic-release/release-notes-generator@^10.0.3
            @semantic-release/changelog@^6.0.3
            @semantic-release/git@^10.0.1
            conventional-changelog-conventionalcommits@^7.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
